.TH naxsi-ui-intercept 1 "2012-05-09"
.SH NAME
naxsi-ui-intercept \- Wrapper script to launch the interceptor daemon for the
naxsi-ui tool.
.SH SYNOPSIS
.B naxsi-ui-intercept
.SH DESCRIPTION
.PP
naxsi-ui-intercept is the interceptor part of naxsi-ui which monitors HTTP
requests from naxsi.
.PP
.SH USAGE
naxsi-ui-intercept
.SH SEE ALSO
Website: <http://code.google.com/p/naxsi/>
.SH "AUTHORS"
naxsi was written by Thibault Koechlin <bui@nbs-system.com>. naxsi-ui-intercept
was written by Cyril Lavier <cyril.lavier@davromaniak.eu>.
.PP
This manual page was written by Cyril Lavier <cyril.lavier@davromaniak.eu> for
the Debian project (but may be used by others).
