.TH naxsi-ui-extract 1 "2012-05-09"
.SH NAME
naxsi-ui-extract \- Wrapper script to launch the extractor daemon for the
naxsi-ui tool.
.SH SYNOPSIS
.B naxsi-ui-extract
.SH DESCRIPTION
.PP
naxsi-ui-extract is the extractor part of naxsi-ui which reads the database and
prints reports about blocked requests.
.PP
.SH USAGE
naxsi-ui-extract
.SH SEE ALSO
Website: <http://code.google.com/p/naxsi/>
.SH AUTHORS
naxsi was written by Thibault Koechlin <bui@nbs-system.com>. naxsi-ui-extract
was written by Cyril Lavier <cyril.lavier@davromaniak.eu>.
.PP
This manual page was written by Cyril Lavier <cyril.lavier@davromaniak.eu> for
the Debian project (but may be used by others).
