.TH "nginx" "1" "" "" ""
.SH "NAME"
nginx \- small, powerful, scalable web/proxy server
.SH "SYNOPSIS"
\fBnginx\fR [\fIoptions\fR] <\fIconfiguration file\fR>
.SH "DESCRIPTION"
.PP
\fBNginx\fR ("engine X") is a high\-performance web and reverse proxy server
created by Igor Sysoev. It can be used both as a standalone web server and as a
proxy to reduce the load on back\-end HTTP or mail servers.
.SH "OPTIONS"
.TP
A summary of options is included below:
.TP
\fB\-?\fR,\fB\-h\fR
Show this help.
.TP
\fB\-v\fR
Show version and exit.
.TP
\fB\-V\fR
Show version and configure options then exit.
.TP
\fB\-s\fR \fIsignal\fR
Send signal to a master process: stop, quit, reopen, reload.
.TP
\fB\-p\fR \fIprefix\fR
Set prefix path.
.TP
\fB\-g\fR \fIdirectives\fR
Set global directives out of configuration file.
.TP
\fB\-c\fR <\fIconfiguration file\fR>
Specifies a particular configuration file for nginx to load.
.TP
\fB\-t\fR
Tests nginx configuration and exit.
.TP
.SH "SEE ALSO"
Website: <http://nginx.org/>
.TP
.SH "AUTHORS"
\fBnginx\fR was written by Igor Sysoev <igor@sysoev.ru>.
.TP
This manual page was written by Jose Parrella <joseparrella@cantv.net> and
Kartik Mistry <kartik@debian.org>, for the Debian project (but may be used
by others).
